const { heroui } = require("@heroui/react");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './contexts/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
    './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx,mjs}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-montserrat)', 'Montserrat', 'system-ui', 'sans-serif'],
        montserrat: ['var(--font-montserrat)', 'Montserrat', 'system-ui', 'sans-serif'],
        inter: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        poppins: ['var(--font-poppins)', 'Poppins', 'system-ui', 'sans-serif'],
        raleway: ['var(--font-raleway)', 'Raleway', 'system-ui', 'sans-serif'],
      },
      colors: {
        'theme-bg': {
          main: 'var(--color-bg-main, #F3F4F6)',
          card: 'var(--color-bg-card, #FFFFFF)',
          sidebar: 'var(--color-bg-sidebar, #FFFFFF)',
          hover: 'var(--color-bg-hover, #EFF6FF)',
        },
        'theme-text': {
          primary: 'var(--color-text-primary, #111827)',
          secondary: 'var(--color-text-secondary, #6B7280)',
        },
        'theme-border': {
          DEFAULT: 'var(--color-border, #E5E7EB)',
        },
      },
      backgroundColor: {
        'theme-main': 'var(--color-bg-main, #F3F4F6)',
        'theme-card': 'var(--color-bg-card, #FFFFFF)',
        'theme-sidebar': 'var(--color-bg-sidebar, #FFFFFF)',
        'theme-hover': 'var(--color-bg-hover, #EFF6FF)',
      },
      zIndex: {
        'mira': '2147483647', // Maximum z-index for MIRA to appear above everything
      },
    },
  },
  darkMode: "class",
  plugins: [
    heroui({
      themes: {
        light: {
          colors: {
            background: "#F8FAFC",
            foreground: "#11181C",
            primary: {
              50: "#EFF6FF",
              100: "#DBEAFE",
              200: "#BFDBFE",
              300: "#93C5FD",
              400: "#60A5FA",
              500: "#3B82F6",
              600: "#2563EB",
              700: "#1D4ED8",
              800: "#1E40AF",
              900: "#1E3A8A",
              DEFAULT: "#3B82F6",
              foreground: "#FFFFFF",
            },
            secondary: {
              50: "#F0F9FF",
              100: "#E0F2FE",
              200: "#BAE6FD",
              300: "#7DD3FC",
              400: "#38BDF8",
              500: "#0EA5E9",
              600: "#0284C7",
              700: "#0369A1",
              800: "#075985",
              900: "#0C4A6E",
              DEFAULT: "#0EA5E9",
              foreground: "#FFFFFF",
            },
            success: {
              50: "#ECFDF5",
              100: "#D1FAE5",
              200: "#A7F3D0",
              300: "#6EE7B7",
              400: "#34D399",
              500: "#10B981",
              600: "#059669",
              700: "#047857",
              800: "#065F46",
              900: "#064E3B",
              DEFAULT: "#10B981",
              foreground: "#FFFFFF",
            },
            warning: {
              50: "#FFFBEB",
              100: "#FEF3C7",
              200: "#FDE68A",
              300: "#FCD34D",
              400: "#FBBF24",
              500: "#F59E0B",
              600: "#D97706",
              700: "#B45309",
              800: "#92400E",
              900: "#78350F",
              DEFAULT: "#F59E0B",
              foreground: "#000000",
            },
            danger: {
              50: "#FEF2F2",
              100: "#FEE2E2",
              200: "#FECACA",
              300: "#FCA5A5",
              400: "#F87171",
              500: "#EF4444",
              600: "#DC2626",
              700: "#B91C1C",
              800: "#991B1B",
              900: "#7F1D1D",
              DEFAULT: "#EF4444",
              foreground: "#FFFFFF",
            },
          },
        },
        dark: {
          colors: {
            background: "#09090b",
            foreground: "#e4e4e7",
            primary: {
              50: "#1E3A8A",
              100: "#1E40AF",
              200: "#1D4ED8",
              300: "#2563EB",
              400: "#3B82F6",
              500: "#60A5FA",
              600: "#93C5FD",
              700: "#BFDBFE",
              800: "#DBEAFE",
              900: "#EFF6FF",
              DEFAULT: "#60A5FA",
              foreground: "#000000",
            },
            secondary: {
              50: "#0C4A6E",
              100: "#075985",
              200: "#0369A1",
              300: "#0284C7",
              400: "#0EA5E9",
              500: "#38BDF8",
              600: "#7DD3FC",
              700: "#BAE6FD",
              800: "#E0F2FE",
              900: "#F0F9FF",
              DEFAULT: "#38BDF8",
              foreground: "#000000",
            },
            success: {
              DEFAULT: "#34D399",
              foreground: "#000000",
            },
            warning: {
              DEFAULT: "#FBBF24",
              foreground: "#000000",
            },
            danger: {
              DEFAULT: "#F87171",
              foreground: "#000000",
            },
          },
        },
      },
    }),
  ],
}

