jest.mock('next/server', () => ({ NextResponse: { json: (body, init) => new Response(JSON.stringify(body), init) }, after: jest.fn() }))
jest.mock('@/lib/permissions', () => ({ requirePermission: jest.fn(), checkPermission: jest.fn() }))
jest.mock('@/lib/realtimeEvents', () => ({ emitAssetUpdate: jest.fn() }))
jest.mock('@/lib/assetNotifications.server', () => ({ notifyAssetAssignment: jest.fn(), assetNotificationRecipients: jest.fn().mockResolvedValue([]) }))
jest.mock('@/lib/assetsStore.server', () => ({ assetDatabase: jest.fn(), saveAsset: jest.fn(), populateAssets: jest.fn() }))
const { POST } = require('@/app/api/assets/route')
const { requirePermission } = require('@/lib/permissions')
const { assetDatabase, saveAsset, populateAssets } = require('@/lib/assetsStore.server')
const { after } = require('next/server')
test('granted custom roles use the permission contract without an auth.success flag', async () => {
  const asset = { _id: 'asset', name: 'Laptop' }, database = { databaseName: 'test' }
  requirePermission.mockReturnValue(async () => ({ denied: null, user: { role: 'employee' } }))
  assetDatabase.mockResolvedValue(database); saveAsset.mockResolvedValue({ record: asset }); populateAssets.mockResolvedValue([asset])
  const res = await POST(new Request('https://talio.test/api/assets', { method: 'POST', body: JSON.stringify(asset) }))
  expect(res.status).toBe(201); expect(requirePermission).toHaveBeenCalledWith('assets', 'create')
  expect(saveAsset).toHaveBeenCalledWith(database, expect.any(Object), asset, expect.objectContaining({ permissionGranted: true })); expect(after).toHaveBeenCalled()
})
test('returns permission denial unchanged', async () => {
  requirePermission.mockReturnValue(async () => ({ denied: new Response('denied', { status: 403 }) }))
  expect((await POST(new Request('https://talio.test/api/assets', { method: 'POST' }))).status).toBe(403)
})
