jest.mock('next/server', () => ({ NextResponse: { json: (body, init) => new Response(JSON.stringify(body), init) }, after: jest.fn() }))
jest.mock('@/lib/auth', () => ({ getAuthAndDatabase: jest.fn() }))
jest.mock('@/lib/permissions', () => ({ requirePermission: jest.fn() }))
jest.mock('@/lib/pushNotification', () => ({ sendPushToUser: jest.fn() }))
jest.mock('@/lib/realtimeEvents', () => ({ emitRealtimeEvent: jest.fn() }))
jest.mock('@/lib/eventBus', () => ({ emitEvent: jest.fn(), EVENTS: {} }))
jest.mock('@/lib/supportStore.server', () => ({ supportDatabase: jest.fn(), mutateTicket: jest.fn(), populateTickets: jest.fn() }))
const { PUT, PATCH } = require('@/app/api/helpdesk/[id]/route')
const { requirePermission } = require('@/lib/permissions')
const { supportDatabase, mutateTicket, populateTickets } = require('@/lib/supportStore.server')
const { after } = require('next/server')
const id = '111111111111111111111111'
beforeEach(() => { jest.clearAllMocks(); requirePermission.mockReturnValue(async () => ({ denied: null, user: {}, tenant: { databaseName: 'test' } })); supportDatabase.mockResolvedValue({}); mutateTicket.mockResolvedValue({ _id: id }); populateTickets.mockResolvedValue([{ _id: id }]) })
test.each([PUT, PATCH])('status-only update is supported', async handler => {
  const res = await handler(new Request('https://talio.test/api/helpdesk/' + id, { method: 'PUT', body: JSON.stringify({ status: 'in-progress' }) }), { params: Promise.resolve({ id }) })
  expect(res.status).toBe(200); expect(mutateTicket).toHaveBeenCalledWith({}, {}, { status: 'in-progress' }, expect.objectContaining({ id, permissionGranted: true })); expect(after).toHaveBeenCalledTimes(1)
})
test('malformed JSON never reaches persistence', async () => {
  const res = await PUT(new Request('https://talio.test/api/helpdesk/' + id, { method: 'PUT', body: '{' }), { params: Promise.resolve({ id }) })
  expect(res.status).toBe(400); expect(mutateTicket).not.toHaveBeenCalled()
})
test('missing tenant assignee propagates as 404', async () => {
  mutateTicket.mockRejectedValue(Object.assign(new Error('Assigned employee not found'), { status: 404 }))
  const res = await PUT(new Request('https://talio.test/api/helpdesk/' + id, { method: 'PUT', body: JSON.stringify({ assignedTo: id }) }), { params: Promise.resolve({ id }) })
  expect(res.status).toBe(404)
})
