import { getOrCreateImageVariant, imageVariantPaths, standardImageVariant } from '@/lib/platform/imageVariants.server'
import { getTenantBlob, uploadTenantBlob } from '@/lib/platform/blobStorage.server'

jest.mock('@/lib/platform/blobStorage.server', () => ({
  buildTenantBlobPath: o => `${o.tenantId}/${o.ownerId}/${o.id}/${o.filename}`,
  getTenantBlob: jest.fn(), uploadTenantBlob: jest.fn(),
}))
const identity = { tenantId: 'tenant-a', dataset: 'dataset-a', id: 'image-a', sha256: 'hash-a' }
beforeEach(() => jest.resetAllMocks())
test('bounds variants and preserves width-only/custom resize semantics', () => {
  for (const size of [128, 256, 512, 1024]) expect(standardImageVariant(size, size, 80)).toBe(size)
  expect(standardImageVariant(256, null, 80)).toBeNull()
  expect(standardImageVariant(256, 512, 80)).toBeNull()
  expect(standardImageVariant(256, 256, 90)).toBeNull()
  expect(imageVariantPaths(identity)).toHaveLength(4)
  expect(imageVariantPaths(identity)).not.toEqual(imageVariantPaths({ ...identity, tenantId: 'tenant-b' }))
  expect(imageVariantPaths(identity)).not.toEqual(imageVariantPaths({ ...identity, sha256: 'hash-b' }))
})
test('cache hit avoids original download, resize and upload', async () => {
  const stream = new Blob(['cached']).stream(), generate = jest.fn()
  getTenantBlob.mockResolvedValue({ statusCode: 200, stream })
  expect(await getOrCreateImageVariant(identity, 256, generate)).toBe(stream)
  expect(generate).not.toHaveBeenCalled()
  expect(uploadTenantBlob).not.toHaveBeenCalled()
  expect(getTenantBlob).toHaveBeenCalledWith(imageVariantPaths(identity)[1], { access: 'private' })
})
test.each([false, true])('cache miss or outage serves generated bytes (outage=%s)', async outage => {
  if (outage) getTenantBlob.mockRejectedValue(new Error('offline'))
  else getTenantBlob.mockResolvedValue(null)
  uploadTenantBlob.mockRejectedValue(new Error('collision'))
  const generate = jest.fn(async () => Buffer.from('thumbnail'))
  const stream = await getOrCreateImageVariant(identity, 256, generate)
  expect(await new Response(stream).text()).toBe('thumbnail')
  expect(generate).toHaveBeenCalledTimes(1)
  expect(uploadTenantBlob).toHaveBeenCalledWith(expect.objectContaining({ access: 'private', contentType: 'image/webp' }))
})
test('unsupported sizes do not read or write storage', async () => {
  await expect(getOrCreateImageVariant(identity, 999, jest.fn())).rejects.toThrow('Unsupported')
  expect(getTenantBlob).not.toHaveBeenCalled()
})
test('generation checks for a concurrent source deletion after upload', async () => {
  getTenantBlob.mockResolvedValue(null)
  const validate = jest.fn(async () => {
    expect(uploadTenantBlob).toHaveBeenCalledTimes(1)
  })
  await getOrCreateImageVariant(identity, 256, async () => Buffer.from('thumbnail'), validate)
  expect(validate).toHaveBeenCalledTimes(1)
})
