'use client'

function formatDate(value) {
  return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(value))
}
export async function createOfferLetterFile({ candidate, jobTitle, designation, joiningDate, salary, notes }) {
  const { jsPDF } = await import('jspdf')
  const pdf = new jsPDF({ unit: 'pt', format: 'a4' })
  const fullName = `${candidate.firstName || ''} ${candidate.lastName || ''}`.trim()
  const role = designation || jobTitle || 'the selected position'

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(22)
  pdf.text('Offer of Employment', 48, 64)
  pdf.setFontSize(10)
  pdf.setTextColor(90)
  pdf.text(`Generated by Talio HRMS · ${formatDate(new Date())}`, 48, 84)

  pdf.setTextColor(20)
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(12)
  const paragraphs = [
    `Dear ${fullName},`,
    `We are pleased to offer you the position of ${role}. Your proposed joining date is ${formatDate(joiningDate)}.`,
    `Your annual compensation will be INR ${Number(salary).toLocaleString('en-IN')}, subject to statutory deductions and the organisation's policies.`,
    notes ? `Additional terms: ${notes}` : null,
    'This offer is subject to successful identity verification and acceptance of the organisation policies shared during onboarding.',
    'Please confirm your acceptance through the Talio recruitment workflow.',
    'Sincerely,\nHuman Resources',
  ].filter(Boolean)

  let y = 132
  for (const paragraph of paragraphs) {
    const lines = pdf.splitTextToSize(paragraph, 500)
    pdf.text(lines, 48, y)
    y += lines.length * 17 + 18
  }

  const safeName = fullName.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase() || 'candidate'
  return new File([pdf.output('arraybuffer')], `offer-letter-${safeName}.pdf`, { type: 'application/pdf' })
}
