'use client'

import { Component, useEffect, useState } from 'react'
import dynamic from 'next/dynamic'

const ImageGeneration = dynamic(() => import('img-fx').then(module => module.ImageGeneration), { ssr: false })
const EMPTY_IMAGES = []

class EffectBoundary extends Component {
  state = { failed: false }
  static getDerivedStateFromError() { return { failed: true } }
  render() { return this.state.failed ? this.props.fallback : this.props.children }
}

export default function MiraGeneratedImage({ image }) {
  const [src, setSrc] = useState('')
  const [error, setError] = useState('')
  const [animate, setAnimate] = useState(false)
  const [revealed, setRevealed] = useState(false)
  useEffect(() => {
    const media = window.matchMedia('(prefers-reduced-motion: reduce)')
    let gl
    try { gl = document.createElement('canvas').getContext('webgl2') } catch {}
    const supported = Boolean(gl)
    gl?.getExtension('WEBGL_lose_context')?.loseContext()
    const update = () => setAnimate(supported && !media.matches)
    update(); media.addEventListener('change', update)
    return () => media.removeEventListener('change', update)
  }, [])
  useEffect(() => {
    setError(''); setSrc(''); setRevealed(false)
    if (image?.status !== 'ready' || !/^[a-f0-9]{24}$/i.test(image.id || '')) return
    const controller = new AbortController()
    let url
    const token = localStorage.getItem('token') || document.cookie.match(/token=([^;]+)/)?.[1] || ''
    fetch(`/api/ai/mira-images/${image.id}`, { headers: { Authorization: `Bearer ${token}` }, signal: controller.signal })
      .then(async response => {
        if (!response.ok) throw new Error('The image could not be loaded. Reopen this chat to retry.')
        const blob = await response.blob()
        if (controller.signal.aborted) return
        url = URL.createObjectURL(blob); setSrc(url)
      }).catch(err => { if (err.name !== 'AbortError') setError(err.message) })
    return () => { controller.abort(); if (url) URL.revokeObjectURL(url) }
  }, [image?.id, image?.status])
  useEffect(() => {
    if (!src) return
    // The loader must not add seconds of waiting after generation completes.
    const timer = setTimeout(() => setRevealed(true), 400)
    return () => clearTimeout(timer)
  }, [src])
  if (!image || image.status === 'failed') return null
  if (error) return <p role="alert" className="my-3 text-sm text-danger">{error}</p>
  const fallback = src
    ? <img src={src} alt="Image generated by MIRA" className="w-full rounded-2xl" />
    : <div className="aspect-square w-full rounded-2xl bg-default-100 flex items-center justify-center text-sm text-default-500">Generating image…</div>
  return <figure className="my-3 w-full max-w-[400px]" aria-label="Generated image" aria-busy={!src}>
    {animate && !revealed ? <EffectBoundary fallback={fallback}>
      <ImageGeneration preset="pixels-organic" images={src ? [src] : EMPTY_IMAGES} autoReveal={Boolean(src)} revealDelayRange={[0.1, 0.1]} onCycle={event => { if (event.phase === 'visible') setRevealed(true) }} style={{ width: '100%' }}>
        <div style={{ width: '100%', aspectRatio: '1', borderRadius: 16 }} className="bg-default-100" />
      </ImageGeneration>
    </EffectBoundary> : fallback}
    <figcaption className="mt-2 text-xs text-default-500" role="status">{src ? 'Generated with Pollinations' : 'Generating image…'}</figcaption>
    {src && <a href={src} download="mira-image.png" className="mt-2 inline-flex rounded-lg border border-divider px-3 py-2 text-sm">Download image</a>}
  </figure>
}
