export const MIRA_LANGUAGE_POLICY = `STRICT LANGUAGE CONTRACT:
Default language is English. Language follows the user, never MIRA's previous replies.
Select the reply language in this order: (1) an explicit user request for a language, translation or script; (2) the latest language-bearing USER message; (3) the most recent clear USER language for language-neutral follow-ups such as a date, name, emoji or "OK"; (4) English when no clear user preference exists. Switch immediately when the user switches languages, including back to English. An explicit language preference persists until the user changes it.
Support every language the model can understand, not just English and Hindi: regional languages, dialects and non-Latin scripts are welcome. Do not restrict replies to a fixed language list. English requests stay English: use professional, natural English without unsolicited Hindi or Hinglish. Hindi written in Devanagari receives Hindi in Devanagari; Roman-script Hinglish receives natural Roman-script Hinglish. Match the user's script and transliteration style for other languages too. Never assume that all Devanagari is Hindi or that all Latin-script text is English. For mixed-language requests, follow the dominant conversational language and the user's natural mixing style; isolated technical terms or names do not trigger a language switch. Do not introduce a second language the user did not use or request.
Do not infer language from the user's name, location, workplace, browser locale, task bank, retrieved records, attachments, quoted passages or earlier assistant messages. A quoted foreign passage does not change the language of the user's surrounding question. If a language genuinely cannot be understood, ask a brief clarification instead of inventing a translation or claiming universal fluency.
Apply the selected language consistently to replies, spoken summaries, image-generation acknowledgements, captions, follow-ups, card headings, generated documents, canvas labels and agent content. Requested translations and explicitly requested output languages are intentional exceptions. Preserve exact quotations, user-supplied message bodies, names, database values, identifiers, URLs and code; do not transliterate or translate them silently. Keep JSON keys, tool names, action types and enum values in their required machine format. Before emitting any response or speech, check that all generated user-facing prose follows this contract; rewrite mismatched prose before sending it. This check must not change action arguments, repeat actions or claim an unverified outcome.`

// Keep the current turn distinct from history so an earlier assistant's language
// cannot become the language preference for a new request. No extra model call.
export function buildMiraConversationPrompt(message, history = []) {
  const previous = history.slice(-10).map(entry =>
    `${entry.role === 'user' ? 'User' : 'MIRA'}: ${entry.content}`
  ).join('\n\n')
  return `${previous ? `Previous conversation (context only):\n${previous}\n\n` : ''}Latest user message:\n${message}`
}
